### ISSUE TITLE
Course administration: no line break

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#10]
When you reduce the window width in the course administration, the content looks like this:

![mdl_course_admin_users](https://user-images.githubusercontent.com/406414/29707939-4e2a71a8-8987-11e7-965b-d85d6bed0236.png)

When you change:
```css
.col-sm-3 {
    float: left;
    width: 25%;
}
```
to:
```css
.col-sm-3 {
    float: none;
    width: 25%;
}
```
it looks like this:

![mdl_course_admin_users_fixed](https://user-images.githubusercontent.com/406414/29708019-996e7024-8987-11e7-9d2e-bc688f39df2b.png)
