### ISSUE TITLE
Title position not vertical centered

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#3]
It may be occurd only at us, maybe because of our logo, but if not, this is how to fix it:

We had the problem, that the title was not vertical centered within the navbar:
![mdl_logo_position_pre](https://user-images.githubusercontent.com/406414/29112630-c03b5884-7cee-11e7-9597-66b4a7d7d751.png)

We fixed this with:

```css
.navbar-light .navbar-brand.has-logo {
    color: #fff;
    margin-top: -0.2rem;
}
```

![mdl_logo_position_post](https://user-images.githubusercontent.com/406414/29112631-c03c13c8-7cee-11e7-896c-d0aea0c1e764.png)
